# Generated by Django 4.0.6 on 2022-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
        ),
    ]
