# Generated by Django 4.0.6 on 2022-07-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_create'], 'verbose_name': 'Основые задачи', 'verbose_name_plural': 'Основные задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.categories', verbose_name='Категории'),
        ),
    ]
